<?php

/**
 * изменить порядок выполнения hook_form_alter
 * хук этого модуля выполняеть последним
 * нужно для
 */
function helper_module_implements_alter(&$implementations, $hook) {
  // Name of the hook.
//  if ($hook != 'form_alter') {
//    return;
//  }
//  $module = 'helper';
//  $group = $implementations[$module];
//  unset($implementations[$module]);
//  $implementations[$module] = $group;
}

/**
 * hook_form_alter
 */
function helper_form_alter(array &$form, array &$form_state = array(), $form_id = NULL)
{
  if ($form_id) {
    switch ($form_id) {
      /** -------------------------- Блок поиска ---------------------------- */
      case 'search_block_form':
        $form['search_block_form']['#attributes']['class'][] = 'input-sm';
        $form['search_block_form']['#theme_wrappers'] = array('vagro_search_form_wrapper');
        break;

    }
  }
}

/**
 * -------------------------- Блоки --------------------------------------------
 * функции, определяющие видимость блоков при использовании модуля
 * Extended block visibility
 * https://www.drupal.org/project/extended_block_visibility
 */
function _vagro_system_main_menu_block_visibility()
{
  return (user_is_anonymous()) ? false : true;
}

/**
 * сформировать имя пользователя
 */
function _user_name($user)
{
  $user_wrapper = entity_metadata_wrapper('user', $user);
  return $user_wrapper->field_user_name->value() . ' ' . $user_wrapper->field_user_surname->value();
}

