<?php

include 'includes/helper.blocks.inc';

/**
 * изменить порядок выполнения hook_form_alter
 * хук этого модуля выполняеть последним
 * нужно для
 */
function helper_module_implements_alter(&$implementations, $hook) {
  // Name of the hook.
//  if ($hook != 'form_alter') {
//    return;
//  }
//  $module = 'helper';
//  $group = $implementations[$module];
//  unset($implementations[$module]);
//  $implementations[$module] = $group;
}

/**
 * hook_form_alter
 */
function helper_form_alter(&$form, &$form_state = array(), $form_id = NULL)
{
  if ($form_id) {
    switch ($form_id) {
      /** -------------------------- Блок поиска ---------------------------- */
      case 'search_block_form':
        // изменить размер строки и функцию темизации
        $form['search_block_form']['#attributes']['class'][] = 'input-sm';
        $form['search_block_form']['#theme_wrappers'] = array('vagro_search_form_wrapper');
        break;

    }
  }
}



