<?php
/**
 * создание сущности выполнено на примере
 * http://www.drupaler.by/lessons/kak-sozdat-sushchnost-v-drupal
 */

include 'includes/post.entity.inc';
include 'includes/post.context.inc';
include 'includes/post.friends.inc';
//include 'includes/post.pages.inc';
//include 'includes/post.admin.inc';

/**
 * Implements hook_menu().
 */
function post_menu() {
  // Top level "post" container.
  $items['admin/config/post'] = array(
    'title' => 'Post',
    'description' => 'Administration tools.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/post/posts'] = array(
    'title' => 'Posts',
    'description' => 'Configure general post settings, fields, and displays.',
    'page callback' => 'post_admin_posts',
    'access arguments' => array('administer posts'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/post.admin.inc',
  );
  $items['admin/config/post/posts/list'] = array(
    'title' => 'Posts',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['stream'] = array(
    'title' => 'Stream',
    'page callback' => 'stream_page',
    'access callback' => 'post_access',
    'access arguments' => array('create', 'post'),
    'file' => 'includes/post.pages.inc',
    'type' => MENU_CALLBACK,
  );
  // Friends page
  $items['friends'] = array(
    'title' => 'Friends',
    'page callback' => 'post_friends_page',
    'access callback' => TRUE,
    'weight' => 10,
    'menu_name' => 'main-menu',
  );
  // Страница создания Записи.
//  $items['post/add'] = array(
//    'title' => 'Add post',
//    'page callback' => 'post_page_add',
//    'access callback' => 'post_access',
//    'access arguments' => array('create', 'post'),
//    'file' => 'includes/post.pages.inc',
//  );
//  // Страница просмотра Записи.
//  $items['post/%post'] = array(
//    'title callback' => 'post_page_title',
//    'title arguments' => array(1),
//    'page callback' => 'post_page_view',
//    'page arguments' => array(1),
//    'access callback' => 'post_access',
//    'access arguments' => array('view', 'post', 1),
//    'file' => 'includes/post.pages.inc',
//  );
//  $items['post/%post/view'] = array(
//    'title' => 'View',
//    'type' => MENU_DEFAULT_LOCAL_TASK,
//    'weight' => 0,
//  );
  // Страница редактирования Записи.
  $items['post/%post/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'post_page_edit',
    'page arguments' => array(1),
    'access callback' => 'post_access',
    'access arguments' => array('update', 'post', 1),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/post.pages.inc',
  );
  // Страница удаления Записи.
  $items['post/%post/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('post_delete_confirm', 1),
    'access callback' => 'post_access',
    'access arguments' => array('delete', 'post', 1),
    'file' => 'includes/post.pages.inc',
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function post_permission() {
  return array(
    'configure post settings' => array(
      'title' => t('Configure post settings'),
      'description' => t('Allows users to configure post settings.'),
      'restrict access' => TRUE,
    ),
    'administer posts' => array(
      'title' => t('Administer posts'),
      'restrict access' => TRUE,
    ),
    'edit any posts' => array(
      'title' => t('Edit any posts'),
      'restrict access' => TRUE,
    ),
    'edit own posts' => array(
      'title' => t('Edit own post'),
      'restrict access' => TRUE,
    ),
    'delete any posts' => array(
      'title' => t('Delete any post'),
      'restrict access' => TRUE,
    ),
    'delete own posts' => array(
      'title' => t('Delete own post'),
      'restrict access' => TRUE,
    ),
    'create posts' => array(
      'title' => t('Create new post'),
    ),
    'view posts' => array(
      'title' => t('View posts'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function post_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'post') . '/views',
  );
}


/**
 * --------------------------------------- Форма ------------------------------------------------
 */
function post_form($form, &$form_state, $post = NULL)
{
  global $user;

  if ($post) $form_state['#post'] = $post;

  $photo_style = 'thumbnail';
  $photo_uri = 'public://default_images/no_photo.png';
  if ($account = user_load($user->uid)) {
    if (!empty($account->picture)) $photo_uri = $account->picture->uri;
  }
  $photo = image_style_url($photo_style, $photo_uri);

  $form = [
    '#attributes' => ['class' => ['post-form']],
  ];

  $form['field'] = [
    '#type' => 'container',
    '#attributes' => ['class' => ['post-field-wrap']],
  ];
  $form['field']['photo'] = [
    '#markup' => '<img src="' . $photo . '" class="img-circle"/>',
  ];
  $form['field']['message'] = [
    '#type' => 'textarea',
    '#rows' => 1,
    '#default_value' => empty($post->message) ? '' : $post->message,
    '#attributes' => [
      'class' => ['autoExpand'],
      'placeholder' => t('What\'s new?'),
      'data-min-rows' => 1,
    ],
    '#prefix' => '<div class="post-field">',
    '#suffix' => '</div>',
  ];

  $form['actions'] = array(
    '#type' => 'actions',
  );
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => empty($post) ? t('Post') : t('Save'),
    '#attributes' => ['class' => ['pull-right']],
  );

  return $form;
}

function post_form_validate(&$form, &$form_state)
{
  if (drupal_strlen($form_state['values']['message']) < 2) form_set_error('top][message', 'Текст сообщения должен быть не короче 2 символов!');
}

/**
 * при создании Записи
 * определение Отправителя и Получателя сообщения
 * установка Группы в качестве отправителя позволяет её администратору писать
 * в группу от своего имени и от имени группы
 *
 * @param $form
 * @param $form_state
 */
function post_form_submit(&$form, &$form_state)
{
  if (empty($form_state['#post'])) {
    // todo определить отправителя
    // Пользователь или Группа (группа может постить только себе)
    $sentype = 'user';
    $senid = $GLOBALS['user']->uid;

    // определить получателя (контекст)
    $context = _get_post_context();
    $rectype = $context['rectype'];
    $recid = $context['recid'];

    // создать Запись
    $post = entity_create('post', array(
      'senid' => $senid,
      'sentype' => $sentype,
      'recid' => $recid,
      'rectype' => $rectype,
      'created' => time(),
      'message' => $form_state['values']['message'],
    ));
  } else {
    $post = $form_state['#post'];
    $post->message = $form_state['values']['message'];
  }
  entity_save('post', $post);
}

/**
 * --------------------------------------- Блоки ------------------------------------------------
 * Implements hook_block_info().
 */
function post_block_info()
{
  $blocks = array(
    'post_form' => [
      'info' => t('Post form'),
      'cache' => DRUPAL_NO_CACHE,
      'region' => 'content',
      'status' => 1,
      'weight' => 10,
      'visibility' => BLOCK_VISIBILITY_PHP,
      'pages' => '<?php return post_form_helper_blocks(); ?>',
    ],
    'news_menu' => [
      'info' => t('News menu'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
      'region' => 'sidebar_second',
      'status' => 1,
      'weight' => -1,
      'visibility' => BLOCK_VISIBILITY_PHP,
      'pages' => '<?php return news_menu_helper_blocks(); ?>',
    ],
    'friends_menu' => [
      'info' => t('Friends menu'),
      'cache' => DRUPAL_CACHE_PER_USER,
      'region' => 'sidebar_second',
      'status' => 1,
      'weight' => -1,
      'visibility' => BLOCK_VISIBILITY_PHP,
      'pages' => '<?php return friends_menu_helper_blocks(); ?>',
    ],
  );

  return $blocks;
}

/**
 * --------------------------------------- Блоки ------------------------------------------------
 * Implements hook_block_info().
 */
function post_block_info_alter(&$blocks)
{
  // настроить вывод блока Views stream по умолчанию
  $block_settings = array(
    'region' => 'content',
    'status' => 1,
    'weight' => 14,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'pages' => '<?php return stream_helper_blocks(); ?>',
  );
  // при установке модуля блока ещё нет, настройки применятся после сброса кэша
  // todo найти способ применить настройки при установке модуля
  if (isset($blocks['views']['stream-block'])) {
    $blocks['views']['stream-block'] = array_merge($blocks['views']['stream-block'], $block_settings);
  }
  // настроить вывод блока Views stream_profile по умолчанию
  $block_settings['weight'] += 1;
  $block_settings['pages'] = '<?php return stream_profile_helper_blocks(); ?>';
  if (isset($blocks['views']['stream_profile-block'])) {
    $blocks['views']['stream_profile-block'] = array_merge($blocks['views']['stream_profile-block'], $block_settings);
  }
}

/**
 * Implements hook_block_view().
 */
function post_block_view($delta = '')
{
  $block = array();

  switch ($delta) {
    case 'post_form':
      $block['content'] = drupal_get_form('post_form');
      return $block;

    case 'news_menu':
      $block['content'] = _news_menu_block_content();
      return $block;

    case 'friends_menu':
      $block['content'] = _friends_menu_block_content();
      return $block;
  }
}

function _news_menu_block_content()
{
  $tree = menu_tree_page_data('menu-news');

  // Localize the tree.
  if (module_exists('i18n_menu')) {
    $tree = i18n_menu_localize_tree($tree);
  }

  // Build links.
  $profile_nav = menu_tree_output($tree);

  return render($profile_nav);
}


/**
 * --------------------------------------- Views ------------------------------------------------
 */

/**
 * Implements of hook_views_data().
 */
function post_views_data() {
  return array(
    'post' => array(
      'from_friends_filter' => array(
        'group' => t('Custom'),
        'title' => t('Only from friends'),
        'help' => t('Filter posts by friends'),
        'filter' => array(
          'handler' => 'post_handler_filter_from_friends_filter',
        ),
      ),
      'from_current_user_filter' => array(
        'group' => t('Custom'),
        'title' => t('Post sent by current user'),
        'help' => t('Filter posts sent by current user'),
        'filter' => array(
          'handler' => 'post_handler_filter_from_current_user_filter',
        ),
      ),
      'to_current_user_filter' => array(
        'group' => t('Custom'),
        'title' => t('Post sent to current user'),
        'help' => t('Filter posts sent to current user'),
        'filter' => array(
          'handler' => 'post_handler_filter_to_current_user_filter',
        ),
      ),
    ),
  );
}